// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Order {
    "order_number": string;
    "ordering": boolean;
    "ordering_date": string;
    "shipping_date": string;
    "documents": boolean;
    "documents_date": string;
    "telex_release": boolean;
    "telex_rel_date": string;
    "remarks": string;
    "completed": boolean;

    /** Creates a new Order instance. */
    constructor($$source: Partial<Order> = {}) {
        if (!("order_number" in $$source)) {
            this["order_number"] = "";
        }
        if (!("ordering" in $$source)) {
            this["ordering"] = false;
        }
        if (!("ordering_date" in $$source)) {
            this["ordering_date"] = "";
        }
        if (!("shipping_date" in $$source)) {
            this["shipping_date"] = "";
        }
        if (!("documents" in $$source)) {
            this["documents"] = false;
        }
        if (!("documents_date" in $$source)) {
            this["documents_date"] = "";
        }
        if (!("telex_release" in $$source)) {
            this["telex_release"] = false;
        }
        if (!("telex_rel_date" in $$source)) {
            this["telex_rel_date"] = "";
        }
        if (!("remarks" in $$source)) {
            this["remarks"] = "";
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Order instance from a string or object.
     */
    static createFrom($$source: any = {}): Order {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Order($$parsedSource as Partial<Order>);
    }
}
