// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddDetail(orderNumber: string, cells: string[]): $CancellablePromise<boolean> {
    return $Call.ByID(653223581, orderNumber, cells);
}

export function AddOrder(orderNumber: string): $CancellablePromise<$models.Order | null> {
    return $Call.ByID(754755204, orderNumber).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteDetail(orderNumber: string, index: number): $CancellablePromise<boolean> {
    return $Call.ByID(3543953363, orderNumber, index);
}

export function DeleteOrder(orderNumber: string): $CancellablePromise<boolean> {
    return $Call.ByID(2568802362, orderNumber);
}

export function DuplicateDetail(orderNumber: string, index: number): $CancellablePromise<boolean> {
    return $Call.ByID(3132513455, orderNumber, index);
}

export function GetColumnWidths(): $CancellablePromise<string> {
    return $Call.ByID(190634844);
}

export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(1914035678);
}

export function GetDetailColWidths(): $CancellablePromise<string> {
    return $Call.ByID(763981457);
}

export function GetSortDir(): $CancellablePromise<string> {
    return $Call.ByID(1894532326);
}

export function GetTodayDate(): $CancellablePromise<string> {
    return $Call.ByID(2583517708);
}

export function GetWindowSize(): $CancellablePromise<string> {
    return $Call.ByID(2006378150);
}

export function LoadOrders(): $CancellablePromise<$models.Order[]> {
    return $Call.ByID(1955172048).then(($result: any) => {
        return $$createType2($result);
    });
}

export function MarkCompleted(orderNumber: string): $CancellablePromise<boolean> {
    return $Call.ByID(1428049, orderNumber);
}

export function ReloadOrders(): $CancellablePromise<$models.Order[]> {
    return $Call.ByID(401026061).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RenameOrder(oldNumber: string, newNumber: string): $CancellablePromise<boolean> {
    return $Call.ByID(1072795837, oldNumber, newNumber);
}

export function SaveColumnWidths(widths: string): $CancellablePromise<void> {
    return $Call.ByID(321196975, widths);
}

export function SaveDetailColWidths(widths: string): $CancellablePromise<void> {
    return $Call.ByID(632459284, widths);
}

export function SaveSortDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(527480771, dir);
}

export function SaveWindowSize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(1592366789, width, height);
}

export function SetConfigPath(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2880072914, path);
}

export function UnmarkCompleted(orderNumber: string): $CancellablePromise<boolean> {
    return $Call.ByID(402226868, orderNumber);
}

export function UpdateDetailRow(orderNumber: string, index: number, row: $models.DetailRow): $CancellablePromise<boolean> {
    return $Call.ByID(1929094691, orderNumber, index, row);
}

export function UpdateOrder(updated: $models.Order): $CancellablePromise<void> {
    return $Call.ByID(2046221620, updated);
}

// Private type creation functions
const $$createType0 = $models.Order.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
